_format_version: "3.0"

services:
  - name: recipe-service
    url: http://recipe-manager:8080
    connect_timeout: 5000
    write_timeout: 10000
    read_timeout: 10000
    retries: 3

routes:
  - name: recipes-api
    service: recipe-service
    protocols: [http, https]
    methods: [GET, POST, PUT, DELETE, PATCH]
    paths: [/api/v1/recipes]
    strip_path: false

  - name: health-check
    service: recipe-service
    protocols: [http, https]
    methods: [GET]
    paths: [/health, /api/health]
    strip_path: false

plugins:
  - name: prometheus
    config:
      per_consumer: true
      status_code_metrics: true
      latency_metrics: true
      bandwidth_metrics: true

  - name: cors
    config:
      origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
      methods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
      headers:
        - Accept
        - Authorization
        - Content-Type
        - X-Request-ID
        - X-Correlation-ID
      credentials: true
      max_age: 3600

  - name: rate-limiting
    route: recipes-api
    config:
      minute: 1000
      hour: 10000
      day: 100000
      policy: local
      fault_tolerant: true

  - name: request-size-limiting
    route: recipes-api
    config:
      allowed_payload_size: 10 