services:
  frontend:
    build:
      context: ${REPOS_DIR:-./repos}/pizzamaker-fe
      dockerfile: deployments/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - recipe-manager
    restart: on-failure

  recipe-manager:
    build:
      context: ${REPOS_DIR:-./repos}/pizzamaker-fe
      dockerfile: deployments/Dockerfile
    ports:
      - "8080:8080"
    environment:
      INGREDIENTS_BALANCER_ADDR: ingredients-balancer:50051
      CONFIG_PATH: /app/configs
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DBNAME: pizzamaker
      DATABASE_USER: user
      DATABASE_PASSWORD: pizzamaker
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  ingredients-balancer:
    build:
      context: ${REPOS_DIR:-./repos}/ingredients-balancer
      dockerfile: deployments/Dockerfile
    ports:
      - "50051:50051"
    restart: on-failure

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzamaker
      MYSQL_USER: user
      MYSQL_PASSWORD: pizzamaker
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=pizzamaker"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql_data:/var/lib/mysql
      - ${REPOS_DIR:-./repos}/recipe-manager/migrations:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql_data:
