services:
  frontend:
    build:
      context: ${REPOS_DIR:-./repos}/pizzamaker-fe
      dockerfile: deployments/Dockerfile
      cache_from:
        - frontend:latest
    image: frontend:latest
    ports:
      - "${PIZZAMAKER_FE_PORT:-3000}:80"
    depends_on:
      - recipe-manager
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  recipe-manager:
    build:
      context: ${REPOS_DIR:-./repos}/recipe-manager
      dockerfile: deployments/Dockerfile
      cache_from:
        - recipe-manager:latest
    image: recipe-manager:latest
    ports:
      - "${RECIPE_MANAGER_PORT:-8080}:8080"
    environment:
      CALCULATOR_ADDR: calculator:50051
      INGREDIENTS_BALANCER_ADDR: ingredients-balancer:50052
      CONFIG_PATH: /app/configs
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_DBNAME: pizzamaker
      DATABASE_USER: user
      DATABASE_PASSWORD: pizzamaker
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  ingredients-balancer:
    build:
      context: ${REPOS_DIR:-./repos}/ingredients-balancer
      dockerfile: deployments/Dockerfile
      cache_from:
        - ingredients-balancer:latest
    image: ingredients-balancer:latest
    ports:
      - "${INGREDIENTS_BALANCER_PORT:-50052}:50051"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  calculator:
    build:
      context: ${REPOS_DIR:-./repos}/calculator
      dockerfile: deployments/Dockerfile
      cache_from:
        - calculator:latest
    image: calculator:latest
    ports:
      - "${CALCULATOR_PORT:-50051}:50051"
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pizzamaker
      MYSQL_USER: user
      MYSQL_PASSWORD: pizzamaker
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "--password=pizzamaker"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - mysql_data:/var/lib/mysql
      - ${REPOS_DIR:-./repos}/recipe-manager/migrations:/docker-entrypoint-initdb.d
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

volumes:
  mysql_data:
