# Traefik Configuration for PizzaMaker Local Development

global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true  # Only for local development

entryPoints:
  web:
    address: ":8000"
  websecure:
    address: ":8443"

providers:
  # Docker provider for auto-discovery
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true
    addRoutersLabels: true

accessLog:
  format: json
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

log:
  level: INFO
  format: json

ping:
  entryPoint: "web"
