cluster.name: "pizzamaker-logs"
node.name: "elasticsearch-logs"

# Network settings
network.host: 0.0.0.0
http.port: 9200
discovery.type: single-node

# Security disabled for local development
xpack.security.enabled: false

bootstrap.memory_lock: false
indices.memory.index_buffer_size: 10%

action.auto_create_index: true
action.destructive_requires_name: false

logger.org.elasticsearch.discovery: WARN

cluster.routing.allocation.disk.threshold_enabled: true
cluster.routing.allocation.disk.watermark.low: 85%
cluster.routing.allocation.disk.watermark.high: 90%
cluster.routing.allocation.disk.watermark.flood_stage: 95% 